---
- hosts: local #/etc/ansible/hosts.cfg
  remote_user: ubuntuuser
  tasks:
    - name: Install ElasticSearch
      apt: name=elasticsearch state=latest
      become: yes
      become_method: sudo

    - name: Add Elastic to apt repository and update
      become: yes
      become_method: sudo
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
        echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-6.x.list
        apt update

    - name: Install Filebeat
      become: yes
      become_method: sudo
      command: apt install filebeat
    # do some stuff here to update the filebeat config

    - name: Install Kibana
      become: yes
      become_method: sudo
      command: apt install kibana

    - service:
        name: filebeat
        state: started

    - service:
        name: kibana
        state: started
