---
- hosts: local #/etc/ansible/hosts.cfg
  roles:
      # Using forked, supports 6.x: https://github.com/andyshinn/ansible-filebeat.git
    - role: ansible-filebeat
      become: yes
      become_method: sudo
  remote_user: ubuntuuser
  tasks:
    #
    # Debian Tasks
    #
    - name: Install ElasticSearch
      apt: name=elasticsearch state=latest
      become: yes
      become_method: sudo
      when: ansible_os_family == "Debian"

    - name: Install Kibana
      become: yes
      become_method: sudo
      command: apt install kibana
      when: ansible_os_family == "Debian"

    #
    # OSX Tasks
    #

    #
    # RHEL Tasks
    #
