---
- hosts: local #/etc/ansible/hosts.cfg
  remote_user: ubuntuuser
  pre_tasks:
    #
    # Debian Tasks
    #
    - name: Install ElasticSearch
      apt: name=elasticsearch state=latest
      become: yes
      become_method: sudo
      when: ansible_os_family == "Debian"
  roles:
      # Using forked, supports 6.x: https://github.com/andyshinn/ansible-filebeat.git
    - role: ansible-filebeat
      become: yes
      become_method: sudo

    # - name: Install Kibana
    #   become: yes
    #   become_method: sudo
    #   command: apt install kibana
    #   when: ansible_os_family == "Debian"

    #
    # OSX Tasks
    #

    #
    # RHEL Tasks
    #
