---
- hosts: local
  remote_user: ubuntuuser
  tasks:
    - service:
        name: elasticsearch
        state: started
    - service:
        name: kibana
        state: started
        # when: ansible_os_family == "Debian"

